apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: gokhanyilmaz <gokhanyilmaz>
    commit.image.appsody.dev/committer: gokhanyilmaz <gokhanyilmaz>
    commit.image.appsody.dev/date: Sat Nov 16 18:19:31 2019 +0300
    commit.image.appsody.dev/message: team file deleted
    image.opencontainers.org/created: "2019-11-16T18:19:56+03:00"
    image.opencontainers.org/documentation: https://github.com/GkhnYlmz/jenga-bank
    image.opencontainers.org/revision: f49ce0284cc91a5976fc11cc1f3876e4e5bf3c33-modified
    image.opencontainers.org/source: https://github.com/GkhnYlmz/jenga-bank/tree/master
    image.opencontainers.org/url: https://github.com/GkhnYlmz/jenga-bank
    stack.appsody.dev/configured: appsody/java-microprofile:0.2
    stack.appsody.dev/created: 2019-11-15T10:51:40+0000
    stack.appsody.dev/revision: 0a6c857b8506ef76f8a6ad8626a021e8eeaf68f0
    stack.appsody.dev/tag: appsody/java-microprofile:0.2.19
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: jenga-bank
    stack.appsody.dev/version: 0.2.11
  name: jenga-bank
  namespace: bank-in-a-box
spec:
  applicationImage: dev.local/jenga-bank
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
status: {}
